import HeaderLabel from '@/components/HeaderLabel';
import './globals.css';
import { Inter } from 'next/font/google';
import { client } from '@/sanity/lib/client';
import { getPromotionalBanner } from '@/sanity/helpers/queries';
import Link from 'next/link';
import netonnetIcon from '@/public/netonnet.svg';
import menuData from '../components/NavigationMenuCategories.json';

import Image from 'next/image';
import NavigationMenu from '@/components/HeaderNavigation';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <div className='bg-gray-300 min-h-screen'>
          <div className='bg-cyan-900 font-medium hidden sm:block'>
            <div className='mx-auto max-w-screen-2xl px-4'>
              {/* Label container */}
              <div className='text-xs flex justify-between py-2'>
                {/* Label text */}
                <span key={'why does this happen'} className='flex gap-2'>
                  <Link
                    key={'Hitta lagershop & öppetider'}
                    className='text-gray-300 hover:underline'
                    href={'example.com'}
                  >
                    Hitta lagershop & öppetider
                  </Link>

                  <Link
                    key={'Kundservice'}
                    className='text-gray-300 hover:underline'
                    href={'example.com'}
                  >
                    | Kundservice |
                  </Link>
                </span>
                <span key={'idk'} className='flex gap-2'>
                  <Link
                    key={'Privatperson'}
                    className='font-bold text-white hover:underline'
                    href={'example.com'}
                  >
                    Privatperson
                  </Link>
                  <Link
                    key={'Företag'}
                    className='text-gray-300 hover:underline'
                    href={'example.com'}
                  >
                    | Företag
                  </Link>
                </span>
              </div>
            </div>
          </div>

          <div className='bg-gray-200'>
            <div className='mx-auto max-w-screen-2xl px-4'>
              <header className='flex justify-between items-center py-4'>
                <div className='flex gap-4'>
                  <Link href={'/'}>
                    <Image src={netonnetIcon} alt='netonnet' />
                  </Link>
                </div>
              </header>
            </div>
          </div>

          <div className='bg-white'>
            <header className='mx-auto max-w-screen-2xl px-4'>
              <NavigationMenu />
            </header>
          </div>

          <main className='mx-auto max-w-screen-2xl px-4 py-2'>{children}</main>
        </div>
      </body>
    </html>
  );
}
