import Link from 'next/link';
import netonnetIcon from '@/public/netonnet.svg';

import Image from 'next/image';
import NavigationMenu from '@/components/HeaderNavigation';

import ShoppingCart from '@/components/ShoppingCart';
import { FaCcMastercard, FaCcStripe, FaCcVisa } from 'react-icons/fa';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className=' bg-gray-100 min-h-screen'>
      <div className='shadow-lg'>
        <div className='mx-auto  max-w-screen-2xl px-4'>
          <header className='  flex justify-between items-center p-6'>
            <div className='flex gap-4'>
              <Link prefetch={false} href={'/'}>
                <Image height={45} src={netonnetIcon} alt='netonnet' />
              </Link>
            </div>

            <span className='flex gap-2'>
              <FaCcStripe className='text-purple-800' size={50} />
              <FaCcMastercard className='text-red-700' size={50} />
              <FaCcVisa className='text-blue-700' size={50} />
            </span>
          </header>
        </div>
      </div>

      <main className='mx-auto max-w-screen-2xl px-4 py-6'>{children}</main>
    </div>
  );
}
