import Link from 'next/link';
import netonnetIcon from '@/public/netonnet.svg';

import Image from 'next/image';
import NavigationMenu from '@/components/HeaderNavigation';
import ShoppingCart from '@/components/ShoppingCart';
import SearchBox from '@/components/SearchBox';
import { FaTruck } from 'react-icons/fa';
import TemporaryDrawer from '@/components/MobileNavigationMenu';
import { BsArrowReturnLeft } from 'react-icons/bs';
import { RiTimerFlashLine } from 'react-icons/ri';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className=' bg-gray-100 min-h-screen'>
      <div className='bg-cyan-900 font-medium hidden sm:block'>
        <div className='mx-auto max-w-screen-2xl px-4'>
          {/* Label container */}
          <div className='text-xs flex justify-between py-2'>
            {/* Label text */}
            <span key={'why does this happen'} className='flex gap-2'>
              <Link
                prefetch={false}
                key={'Hitta lagershop & öppetider'}
                className='text-gray-300 hover:underline'
                href={'example.com'}
              >
                Hitta lagershop & öppetider
              </Link>

              <Link
                prefetch={false}
                key={'Kundservice'}
                className='text-gray-300 hover:underline'
                href={'example.com'}
              >
                | Kundservice |
              </Link>
            </span>
            <span key={'idk'} className='flex gap-2'>
              <Link
                key={'Privatperson'}
                className='font-bold text-white hover:underline'
                href={'example.com'}
              >
                Privatperson
              </Link>
              <Link
                prefetch={false}
                key={'Företag'}
                className='text-gray-300 hover:underline'
                href={'example.com'}
              >
                | Företag
              </Link>
            </span>
          </div>
        </div>
      </div>

      {/* Header desktop view*/}
      <div className='mx-auto max-w-screen-2xl px-4 hidden md:block '>
        <header className='flex justify-between items-center py-4'>
          <div className='flex gap-4'>
            <Link prefetch={false} href={'/'}>
              <Image src={netonnetIcon} alt='netonnet' />
            </Link>
          </div>

          <SearchBox />

          <span className='flex gap-2'>
            <ShoppingCart />
          </span>
        </header>
      </div>
      {/* Header desktop view*/}

      {/* Header mobile view*/}
      <div className='mx-auto max-w-screen-2xl px-4 md:hidden flex flex-col'>
        <header className='flex justify-between items-center py-4'>
          <div className='flex gap-4 items-center'>
            <TemporaryDrawer />
            <Link prefetch={false} href={'/'}>
              <Image src={netonnetIcon} alt='netonnet' />
            </Link>
          </div>

          <span className='flex gap-2'>
            <ShoppingCart />
          </span>
        </header>

        <SearchBox />
      </div>

      <div className='bg-white shadow-lg '>
        <header className='mx-auto max-w-screen-2xl px-4'>
          <NavigationMenu />
        </header>
      </div>

      <main className='mx-auto max-w-screen-2xl px-4 py-2'>{children}</main>

      <footer className=' mt-5'>
        <section className='w-full  text-white font-bold bg-light-blue-900   gap-8'>
          <div className='mx-auto p-6 flex md:flex-row flex-col gap-2 md:gap-0 justify-evenly items-center max-w-screen-lg'>
            <span className='flex items-center flex-col gap-2'>
              <BsArrowReturnLeft className='text-3xl' />
              <h2>30 dagars öppet köp</h2>
            </span>
            <span className='flex items-center flex-col gap-2'>
              <FaTruck className='text-3xl' />
              <h2>Fri frakt från 399:-</h2>
            </span>
            <span className='flex flex-col items-center gap-2'>
              <RiTimerFlashLine className='text-3xl' />
              <h2>Leverans samma dag</h2>
            </span>
          </div>
        </section>

        <section className='w-full  text-black font-bold text-sm md:text-md     gap-8'>
          <div className='mx-auto p-6 flex md:flex-row flex-col justify-evenly items-start md:items-center max-w-screen-2xl'>
            <span className='flex  flex-col gap-1'>
              <h2 className='text-xl text-light-blue-500'>Populära sidor</h2>
              <p>lorem</p>
              <p>lorem</p>
              <p>lorem</p>
              <p>lorem</p>
              <p>lorem</p>
              <p>lorem</p>
              <p>lorem</p>
            </span>

            <span className='flex  flex-col gap-1'>
              <h2 className='text-xl text-light-blue-500'>Kundservice</h2>
              <p>lorem</p>
              <p>lorem</p>
              <p>lorem</p>
              <p>lorem</p>
              <p>lorem</p>
              <p>lorem</p>
              <p>lorem</p>
            </span>

            <span className='flex  flex-col gap-1'>
              <h2 className='text-xl text-light-blue-500'>Om NetOnNet</h2>
              <p>lorem</p>
              <p>lorem</p>
              <p>lorem</p>
              <p>lorem</p>
              <p>lorem</p>
              <p>lorem</p>
              <p>lorem</p>
            </span>
          </div>
        </section>
      </footer>
    </div>
  );
}
